define(['baseView', 'loading', 'emby-input', 'emby-button', 'emby-select', 'emby-checkbox', 'emby-textarea', 'emby-scroller'], function (BaseView, loading) {
    'use strict';

    var pluginId = 'e2688ed7-4bb2-4bba-9e0d-6ccfd1f2d8f3';
    var builtInRules = [
        { name: 'All ages', aliases: ['ALL','0+','0','G','TV-G','TV-Y','U'], age: 0, system: 'GENERIC', priority: 100 },
        { name: 'Parental guidance', aliases: ['PG','TV-PG'], age: 10, conservativeAge: 12, system: 'GENERIC', priority: 90 },
        { name: 'Generic 12+', aliases: ['12','12+','12A','PG12','FSK-12','BR-12'], age: 12, system: 'GENERIC', priority: 120 },
        { name: 'US MPA PG-13', aliases: ['PG-13','PG13'], age: 13, system: 'US_MPA', priority: 200 },
        { name: 'Generic 14+', aliases: ['14','14+','TV-14','AT-14','BR-14'], age: 14, system: 'GENERIC', priority: 120 },
        { name: 'Generic 15+', aliases: ['15','15+','R15+','MA15+','MA 15+','M'], age: 15, system: 'GENERIC', priority: 120 },
        { name: 'Generic 16+', aliases: ['16','16+','FSK-16','BR-16'], age: 16, system: 'GENERIC', priority: 120 },
        { name: 'US MPA R', aliases: ['R'], age: 17, conservativeAge: 18, system: 'US_MPA', priority: 200 },
        { name: 'US TV-MA', aliases: ['TV-MA','TVMA'], age: 17, conservativeAge: 18, system: 'US_TV', priority: 200 },
        { name: 'Generic 18+', aliases: ['18','18+','+18','R18+','NC-17','FSK-18','BR-18','PL-18'], age: 18, system: 'GENERIC', priority: 120 }
    ];
    var presets = { 'age-based': [[0,0,'ALL'],[1,6,'6+'],[7,10,'10+'],[11,12,'12+'],[13,14,'14+'],[15,15,'15+'],[16,17,'16+'],[18,99,'18+']], 'my-simple-ratings': [[0,11,'ALL'],[12,14,'TEEN'],[15,17,'MATURE'],[18,99,'ADULT']], 'japan-eirin': [[0,11,'G'],[12,14,'PG12'],[15,17,'R15+'],[18,99,'R18+']], 'us-tv': [[0,6,'TV-G'],[7,7,'TV-Y7'],[8,13,'TV-PG'],[14,16,'TV-14'],[17,99,'TV-MA']], 'us-film': [[0,9,'G'],[10,12,'PG'],[13,16,'PG-13'],[17,17,'R'],[18,99,'NC-17']], 'europe-generic': [[0,0,'0+'],[1,6,'6+'],[7,10,'10+'],[11,12,'12+'],[13,14,'14+'],[15,15,'15+'],[16,17,'16+'],[18,99,'18+']], 'uk-bbfc': [[0,0,'U'],[1,11,'PG'],[12,14,'12'],[15,17,'15'],[18,99,'18']], 'de-fsk': [[0,0,'FSK-0'],[1,6,'FSK-6'],[7,12,'FSK-12'],[13,16,'FSK-16'],[17,99,'FSK-18']], 'australia': [[0,0,'G'],[1,10,'PG'],[11,14,'M'],[15,17,'MA15+'],[18,99,'R18+']] };

    function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;'); }
    function norm(v) { return String(v || '').trim().toUpperCase().replace(/[^A-Z0-9+]/g, ''); }
    function intOrNull(v) { var text = String(v == null ? '' : v).trim(); if (!text) return null; var n = parseInt(text, 10); return isNaN(n) ? null : Math.max(0, Math.min(99, n)); }
    function setStatus(page, message, error) { var el = page.querySelector(error ? '.configError' : '.configStatus'); el.textContent = message || ''; el.style.display = message ? 'block' : 'none'; }
    function resultValue(result, pascal, camel) { return result && (result[pascal] != null ? result[pascal] : result[camel]) || 0; }
    function runResultMessage(result) { if (result && (result.SkippedBecauseDisabled || result.skippedBecauseDisabled)) return 'Skipped because the plugin is disabled.'; return 'Completed. Scanned ' + resultValue(result, 'ScannedCount', 'scannedCount') + ', matched ' + resultValue(result, 'MatchedCount', 'matchedCount') + ', updated ' + resultValue(result, 'UpdatedCount', 'updatedCount') + ', already standardized ' + resultValue(result, 'AlreadyStandardizedCount', 'alreadyStandardizedCount') + ', missing official rating ' + resultValue(result, 'MissingOfficialRatingCount', 'missingOfficialRatingCount') + ', no matching rule ' + resultValue(result, 'NoMatchingRuleCount', 'noMatchingRuleCount') + '.'; }
    function rollbackResultMessage(result) { if (result && (result.SkippedBecauseDisabled || result.skippedBecauseDisabled)) return 'Skipped because the plugin is disabled.'; return 'Rollback completed. Scanned ' + resultValue(result, 'ScannedCount', 'scannedCount') + ', restored ' + resultValue(result, 'RestoredCount', 'restoredCount') + ', already original ' + resultValue(result, 'AlreadyOriginalCount', 'alreadyOriginalCount') + ', missing history ' + resultValue(result, 'MissingHistoryCount', 'missingHistoryCount') + '.'; }
    function getCustomPresets(page) { try { return JSON.parse(page.querySelector('.customPresetsJson').value || '[]') || []; } catch (err) { return []; } }

    function createRuleRow(rule) {
        var tr = document.createElement('tr');
        var type = rule && rule.MatchType || 'Alias';
        var matchValue = type === 'Regex' ? (rule && rule.Pattern || '') : (rule && rule.Aliases || []).join(', ');
        tr.innerHTML = '<td><label class="rs-check-cell"><input type="checkbox" class="rs-native-check rule-enabled" ' + (rule && rule.Enabled === false ? '' : 'checked') + '></label></td><td><input is="emby-input" class="rule-name rs-rule-input rs-input" placeholder="Korea 15+" value="' + esc(rule && rule.Name) + '"></td><td><select is="emby-select" class="rule-type rs-select"><option value="Alias">Alias</option><option value="Regex">Regex</option></select></td><td><input is="emby-input" class="rule-match rs-rule-input rs-input" placeholder="KR-15, KMRB-15 or ^BR-(\\d{1,2})$" value="' + esc(matchValue) + '"></td><td><input is="emby-input" class="rule-age rs-age-input rs-input" type="number" min="0" max="99" placeholder="15" value="' + esc(rule && rule.MinimumAge || 0) + '"></td><td><input is="emby-input" class="rule-group rs-age-input rs-input" type="number" min="1" placeholder="1" value="' + esc(rule && rule.MinimumAgeFromGroup || '') + '"></td><td class="rs-advanced-rule"><input is="emby-input" class="rule-conservative rs-age-input rs-input" type="number" min="0" max="99" placeholder="18" value="' + esc(rule && rule.ConservativeAge != null ? rule.ConservativeAge : '') + '"></td><td class="rs-advanced-rule"><input is="emby-input" class="rule-lenient rs-age-input rs-input" type="number" min="0" max="99" placeholder="12" value="' + esc(rule && rule.LenientAge != null ? rule.LenientAge : '') + '"></td><td class="rs-advanced-rule"><select is="emby-select" class="rule-restriction rs-select"><option>unknown</option><option>advisory</option><option>restricted</option><option>adult</option></select></td><td><input is="emby-input" class="rule-priority rs-age-input rs-input" type="number" placeholder="1000" value="' + esc(rule && rule.Priority || 1000) + '"></td><td><button is="emby-button" type="button" class="button-flat rule-delete rs-delete"><span>x</span></button></td>';
        tr.querySelector('.rule-type').value = type;
        tr.querySelector('.rule-restriction').value = (rule && rule.Restriction) || 'unknown';
        tr.querySelector('.rule-delete').onclick = function () { tr.remove(); };
        return tr;
    }

    function syncAdvancedRulesVisibility(page) { var show = page.querySelector('.chkShowAdvancedRules').checked; page.querySelector('.customRulesTable').classList.toggle('rs-show-advanced', show); Array.prototype.slice.call(page.querySelectorAll('.customRulesTable .rs-advanced-rule')).forEach(function (el) { el.style.display = show ? 'table-cell' : 'none'; }); }
    function renderRules(page, rules) { page.querySelector('.customRuleRows').innerHTML = ''; (rules || []).forEach(function (r) { page.querySelector('.customRuleRows').appendChild(createRuleRow(r)); }); page.querySelector('.customRulesJson').value = JSON.stringify(rules || [], null, 2); syncAdvancedRulesVisibility(page); }
    function collectRules(page) { return Array.prototype.slice.call(page.querySelectorAll('.customRuleRows tr')).map(function (tr, i) { var type = tr.querySelector('.rule-type').value; var matchValue = tr.querySelector('.rule-match').value.trim(); var aliases = type === 'Alias' ? matchValue.split(',').map(function (v) { return v.trim(); }).filter(Boolean) : []; return { Id: 'custom_rule_' + (i + 1), Name: tr.querySelector('.rule-name').value.trim() || aliases[0] || 'Custom rule', MatchType: type, Aliases: aliases, Pattern: type === 'Regex' ? matchValue : '', MinimumAgeFromGroup: intOrNull(tr.querySelector('.rule-group').value), MinimumAge: intOrNull(tr.querySelector('.rule-age').value) || 0, ConservativeAge: intOrNull(tr.querySelector('.rule-conservative').value), LenientAge: intOrNull(tr.querySelector('.rule-lenient').value), NormalizedLabel: '', System: 'CUSTOM', Restriction: tr.querySelector('.rule-restriction').value || 'unknown', Priority: parseInt(tr.querySelector('.rule-priority').value || '1000', 10), Enabled: tr.querySelector('.rule-enabled').checked, IsCustom: true }; }).filter(function (r) { return r.MatchType === 'Regex' ? r.Pattern : r.Aliases.length; }); }
    function syncPresetOptions(page, selected) { Array.prototype.slice.call(page.querySelectorAll('.selectPreset option[data-custom="true"]')).forEach(function (option) { option.remove(); }); getCustomPresets(page).forEach(function (preset) { if (!preset || !preset.id) return; var option = document.createElement('option'); option.value = preset.id; option.textContent = preset.name || preset.id; option.setAttribute('data-custom', 'true'); page.querySelector('.selectPreset').appendChild(option); }); if (selected) page.querySelector('.selectPreset').value = selected; }
    function presetOptions(page, selected) { var value = selected || 'age-based'; var html = '<option value="age-based">Age-based</option><option value="my-simple-ratings">My Simple Ratings</option><option value="japan-eirin">Japan / Eirin</option><option value="us-tv">United States / TV</option><option value="us-film">United States / Film</option><option value="europe-generic">Europe / Generic</option><option value="uk-bbfc">Europe / UK BBFC</option><option value="de-fsk">Europe / Germany FSK</option><option value="australia">Australia</option>'; getCustomPresets(page).forEach(function (p) { if (p && p.id) html += '<option value="' + esc(p.id) + '">' + esc(p.name || p.id) + '</option>'; }); return html.replace('value="' + esc(value) + '"', 'value="' + esc(value) + '" selected'); }

    function renderAge(page, age) { var selected = page.querySelector('.selectPreset').value; var p = presets[selected]; if (!p) { var custom = getCustomPresets(page).filter(function (preset) { return preset && preset.id === selected; })[0]; p = custom && custom.render ? custom.render.map(function (r) { return [r.min, r.max, r.label]; }) : null; } p = p || presets['age-based']; for (var i = 0; i < p.length; i++) if (age >= p[i][0] && age <= p[i][1]) return p[i][2]; return age ? age + '+' : 'ALL'; }
    function matchRule(rule, input) { if (rule.MatchType === 'Regex') { try { var m = new RegExp(rule.Pattern, 'i').exec(input); if (!m) return null; var age = rule.MinimumAgeFromGroup && m[rule.MinimumAgeFromGroup] ? parseInt(m[rule.MinimumAgeFromGroup], 10) : rule.MinimumAge; return isNaN(age) ? null : { rule: rule, age: Math.max(0, Math.min(99, age)) }; } catch (err) { return null; } } return (rule.Aliases || []).some(function (a) { return norm(a) === norm(input); }) ? { rule: rule, age: rule.MinimumAge } : null; }
    function test(page) { var input = page.querySelector('.txtTestInput').value; var custom = collectRules(page).map(function (r) { r.Priority = (r.Priority || 0) + 10000; return r; }); var all = custom.concat(builtInRules.map(function (r) { return { Name: r.name, MatchType: 'Alias', Aliases: r.aliases, MinimumAge: r.age, ConservativeAge: r.conservativeAge, LenientAge: r.lenientAge, System: r.system, Priority: r.priority }; })); var match = all.map(function (r) { return matchRule(r, input); }).filter(Boolean).sort(function (a,b) { return (b.rule.Priority || 0) - (a.rule.Priority || 0); })[0]; if (!match) { page.querySelector('.testResult').textContent = 'No matching rule. Unknown behavior: ' + page.querySelector('.selectUnknown').value; return; } var age = match.age; if (page.querySelector('.selectPolicy').value === 'Conservative' && match.rule.ConservativeAge != null) age = match.rule.ConservativeAge; if (page.querySelector('.selectPolicy').value === 'Lenient' && match.rule.LenientAge != null) age = match.rule.LenientAge; page.querySelector('.testResult').textContent = 'Matched rule: ' + (match.rule.Name || 'Custom rule') + '\nSystem: ' + (match.rule.System || 'CUSTOM') + '\nInternal age: ' + (age ? age + '+' : 'ALL') + '\nOutput preset: ' + page.querySelector('.selectPreset').value + '\nFinal rating: ' + renderAge(page, age); }
    function validate(rules, presets) { var errors = [], warnings = [], seen = {}; rules.forEach(function (r) { if (r.MinimumAge < 0 || r.MinimumAge > 99) errors.push(r.Name + ': age must be 0-99.'); if (r.MatchType === 'Regex') { if (!r.Pattern) errors.push(r.Name + ': regex pattern is required.'); else try { new RegExp(r.Pattern); } catch (err) { errors.push(r.Name + ': regex pattern is invalid.'); } if (r.MinimumAgeFromGroup != null && r.MinimumAgeFromGroup < 1) errors.push(r.Name + ': age group must be 1 or greater.'); } else { if (!r.Aliases.length) errors.push(r.Name + ': alias is required.'); r.Aliases.forEach(function (a) { var n = norm(a); if (seen[n]) warnings.push('Duplicate alias ' + a + ': higher priority wins.'); seen[n] = true; }); } }); presets.forEach(function (p) { if (!p.id) errors.push('Custom preset id is required.'); (p.render || []).forEach(function (range) { if (range.min > range.max) errors.push((p.name || p.id) + ': render min must be <= max.'); if (!range.label) errors.push((p.name || p.id) + ': render label is required.'); }); }); return { errors: errors, warnings: warnings }; }

    function syncLibrarySelectionState(page) { Array.prototype.slice.call(page.querySelectorAll('.ratingStandardizerLibraryItem')).forEach(function (item) { var checkbox = item.querySelector('.library-check'); item.classList.toggle('is-selected', !!(checkbox && checkbox.checked)); }); }
    function updateLibraryVisibility(page) { page.querySelector('.libraryList').hidden = !page.querySelector('.chkLimitLibraries').checked; page.querySelector('.libraryHint').hidden = page.querySelector('.chkLimitLibraries').checked; syncLibrarySelectionState(page); }
    function selectedLibraries(page) { var selected = {}; Array.prototype.slice.call(page.querySelectorAll('.library-check')).filter(function (b) { return b.checked; }).forEach(function (b) { selected[String(b.value).toLowerCase()] = true; }); return selected; }
    function statusHtml(active) { return active ? '<span class="rs-status-badge rs-status-active">Active</span>' : '<span class="rs-status-badge rs-status-inactive">Inactive: not in Target Libraries</span>'; }
    function updateProfileStatuses(page) { var limiting = page.querySelector('.chkLimitLibraries').checked; var selected = selectedLibraries(page); Array.prototype.slice.call(page.querySelectorAll('.libraryProfileRows tr')).forEach(function (row) { var active = !limiting || selected[String(row.getAttribute('data-library-id') || '').toLowerCase()]; row.querySelector('.profile-status').innerHTML = statusHtml(active); }); }
    function profileRow(page, folder, profile, selectedLookup, limiting) { var id = String(folder.ItemId || folder.Id || ''); var name = folder.Name || 'Unnamed library'; var active = !limiting || selectedLookup[id.toLowerCase()]; var enabled = !!profile; return '<tr class="library-profile-row" data-library-id="' + esc(id) + '" data-library-name="' + esc(name) + '"><td><label class="rs-check-cell"><input type="checkbox" class="rs-native-check profile-enabled" ' + (enabled ? 'checked' : '') + '></label></td><td class="rs-library-name">' + esc(name) + '</td><td><select is="emby-select" class="profile-preset rs-select rs-profile-select">' + presetOptions(page, profile && profile.PresetId) + '</select></td><td><select is="emby-select" class="profile-policy rs-select rs-profile-select"><option value="Conservative">Conservative</option><option value="Nearest">Nearest</option><option value="Lenient">Lenient</option></select></td><td><select is="emby-select" class="profile-unknown rs-select rs-profile-select"><option value="KeepOriginal">Keep original</option><option value="ConvertToUnrated">Mark as NR</option><option value="HideRating">Hide rating</option></select></td><td><select is="emby-select" class="profile-storage rs-select rs-profile-select"><option value="PluginStoreAndTags">Plugin history store + Tags</option><option value="PluginStoreOnly">Plugin history store only</option><option value="TagsOnly">Tags only</option><option value="None">Disabled</option></select></td><td class="fieldDescription profile-status rs-status-col">' + statusHtml(active) + '</td></tr>'; }
    function renderLibraryProfiles(page, folders, config, selectedLookup) { var profiles = {}; (config.LibraryProfiles || []).forEach(function (p) { if (p && p.LibraryId) profiles[String(p.LibraryId).toLowerCase()] = p; }); var limiting = (config.TargetLibraryIds || []).length > 0; page.querySelector('.libraryProfileRows').innerHTML = (folders || []).map(function (folder) { var id = String(folder.ItemId || folder.Id || ''); return profileRow(page, folder, profiles[id.toLowerCase()], selectedLookup, limiting); }).join(''); Array.prototype.slice.call(page.querySelectorAll('.libraryProfileRows tr')).forEach(function (row) { var profile = profiles[String(row.getAttribute('data-library-id')).toLowerCase()]; if (!profile) return; row.querySelector('.profile-policy').value = profile.AmbiguousMappingPolicy || 'Conservative'; row.querySelector('.profile-unknown').value = profile.UnknownRatingBehavior || 'KeepOriginal'; row.querySelector('.profile-storage').value = profile.OriginalRatingStorageMode || 'PluginStoreAndTags'; }); }
    function libraryCard(f, checked, cssClass) { var id = String(f.ItemId || f.Id || ''); return '<label class="ratingStandardizerLibraryItem"><input type="checkbox" class="' + cssClass + '" value="' + esc(id) + '" ' + (checked ? 'checked' : '') + '><span class="ratingStandardizerLibraryContent"><span class="ratingStandardizerLibraryCheck"></span><span class="ratingStandardizerLibraryName">' + esc(f.Name || 'Unnamed library') + '</span></span></label>'; }
    function loadLibraries(page, config) { var selected = {}; (config.TargetLibraryIds || []).forEach(function (id) { selected[String(id).toLowerCase()] = true; }); page.querySelector('.chkLimitLibraries').checked = (config.TargetLibraryIds || []).length > 0; updateLibraryVisibility(page); return ApiClient.getJSON(ApiClient.getUrl('Library/VirtualFolders')).then(function (folders) { page.querySelector('.libraryList').innerHTML = (folders || []).map(function (f) { var id = String(f.ItemId || f.Id || ''); return libraryCard(f, selected[id.toLowerCase()], 'library-check'); }).join(''); page.querySelector('.rollbackLibraryList').innerHTML = (folders || []).map(function (f) { return libraryCard(f, false, 'rollback-library-check'); }).join(''); Array.prototype.slice.call(page.querySelectorAll('.library-check')).forEach(function (b) { b.onchange = function () { syncLibrarySelectionState(page); updateProfileStatuses(page); }; }); Array.prototype.slice.call(page.querySelectorAll('.rollback-library-check')).forEach(function (b) { b.onchange = function () { syncRollbackLibrarySelectionState(page); }; }); syncLibrarySelectionState(page); syncRollbackLibrarySelectionState(page); renderLibraryProfiles(page, folders || [], config, selected); }).catch(function () { page.querySelector('.libraryStatus').textContent = 'Could not load libraries. Existing selection will be kept when saved.'; }); }
    function collectLibraries(page, config) { if (!page.querySelector('.chkLimitLibraries').checked) return []; var boxes = page.querySelectorAll('.library-check'); if (!boxes.length) return config.TargetLibraryIds || []; return Array.prototype.slice.call(boxes).filter(function (b) { return b.checked; }).map(function (b) { return b.value; }); }
    function collectLibraryProfiles(page) { return Array.prototype.slice.call(page.querySelectorAll('.libraryProfileRows tr')).filter(function (row) { return row.querySelector('.profile-enabled').checked; }).map(function (row) { return { LibraryId: row.getAttribute('data-library-id') || '', LibraryName: row.getAttribute('data-library-name') || '', PresetId: row.querySelector('.profile-preset').value, AmbiguousMappingPolicy: row.querySelector('.profile-policy').value, UnknownRatingBehavior: row.querySelector('.profile-unknown').value, OriginalRatingStorageMode: row.querySelector('.profile-storage').value }; }); }

    function syncRollbackLibrarySelectionState(page) { Array.prototype.slice.call(page.querySelectorAll('.rollbackLibraryList .ratingStandardizerLibraryItem')).forEach(function (item) { var checkbox = item.querySelector('.rollback-library-check'); item.classList.toggle('is-selected', !!(checkbox && checkbox.checked)); }); }
    function syncRollbackScope(page) { var scope = page.querySelector('.selectRollbackScope').value; page.querySelector('.rollbackLibraryList').hidden = scope !== 'libraries'; page.querySelector('.rollbackHistoryPanel').hidden = scope !== 'history' && scope !== 'historyDate'; page.querySelector('.rollbackHistoryList').hidden = scope !== 'history'; page.querySelector('.rollbackHistoryDateList').hidden = scope !== 'historyDate'; page.querySelector('.btnSelectAllRollbackHistory').hidden = scope !== 'history'; page.querySelector('.btnClearRollbackHistory').hidden = scope !== 'history'; }
    function selectedRollbackLibraries(page) { return Array.prototype.slice.call(page.querySelectorAll('.rollback-library-check')).filter(function (b) { return b.checked; }).map(function (b) { return b.value; }); }
    function selectedRollbackItems(page) { return Array.prototype.slice.call(page.querySelectorAll('.rollback-history-check')).filter(function (b) { return b.checked; }).map(function (b) { return b.value; }); }
    function selectedRollbackUpdatedAtKeys(page) { return Array.prototype.slice.call(page.querySelectorAll('.rollback-history-date-check')).filter(function (b) { return b.checked; }).map(function (b) { return b.value; }); }
    function rollbackRequest(page) { var scope = page.querySelector('.selectRollbackScope').value; return { UseConfiguredTargetLibraries: scope === 'configured', LibraryIds: scope === 'libraries' ? selectedRollbackLibraries(page) : [], ItemIds: scope === 'history' ? selectedRollbackItems(page) : [], UpdatedAtKeys: scope === 'historyDate' ? selectedRollbackUpdatedAtKeys(page) : [] }; }
    function rollbackSummary(req) { if (req.UpdatedAtKeys.length) return req.UpdatedAtKeys.length + ' selected execution date/time value(s)'; if (req.ItemIds.length) return req.ItemIds.length + ' selected history item(s)'; if (req.LibraryIds.length) return req.LibraryIds.length + ' selected library/libraries'; return 'the current Target Libraries setting'; }
    function setRollbackHistorySelection(page, checked) { Array.prototype.slice.call(page.querySelectorAll('.rollback-history-check')).forEach(function (b) { b.checked = checked; }); }
    function historyDateKey(value) { var date = new Date(value || ''); return isNaN(date.getTime()) ? String(value || '').slice(0, 16) : date.toISOString().slice(0, 16); }
    function historyDateLabel(key) { return key ? key.replace('T', ' ') + ' UTC' : 'Unknown execution date/time'; }
    function rollbackHistoryDateItems(items) { var groups = {}; (items || []).forEach(function (item) { var key = historyDateKey(item.UpdatedAt || item.updatedAt || ''); if (!key) return; groups[key] = (groups[key] || 0) + 1; }); return Object.keys(groups).sort().reverse().map(function (key) { return '<label class="rs-history-item"><input type="checkbox" class="rollback-history-date-check" value="' + esc(key) + '"><span><strong>' + esc(historyDateLabel(key)) + '</strong><span class="rs-history-meta">' + groups[key] + ' history item(s)</span></span></label>'; }).join(''); }
    function loadRollbackHistory(page) { loading.show(); return ApiClient.getJSON(ApiClient.getUrl('Plugins/RatingStandardizer/History?limit=500')).then(function (result) { var items = result && (result.Items || result.items) || []; page.querySelector('.rollbackHistoryDateList').innerHTML = items.length ? rollbackHistoryDateItems(items) : '<div class="fieldDescription">No rating history is available.</div>'; page.querySelector('.rollbackHistoryList').innerHTML = items.length ? items.map(function (item) { var id = item.ItemId || item.itemId || ''; var name = item.Name || item.name || 'Unnamed item'; var original = item.OriginalOfficialRating || item.originalOfficialRating || ''; var finalRating = item.FinalRating || item.finalRating || ''; var updated = item.UpdatedAt || item.updatedAt || ''; var path = item.Path || item.path || ''; return '<label class="rs-history-item"><input type="checkbox" class="rollback-history-check" value="' + esc(id) + '"><span><strong>' + esc(name) + '</strong><span class="rs-history-meta">Original: ' + esc(original) + ' / Current standardized: ' + esc(finalRating) + ' / Updated: ' + esc(updated) + '</span><span class="rs-history-meta">' + esc(path) + '</span></span></label>'; }).join('') : '<div class="fieldDescription">No rating history is available.</div>'; }).catch(function () { setStatus(page, 'Failed to load rollback history.', true); }).then(function () { loading.hide(); }); }

    function timestamp() { return new Date().toISOString().replace(/[:.]/g, '-'); }
    function historyItems(result) { return result && (result.Items || result.items) || []; }
    function downloadJson(filename, data) { var blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); var url = URL.createObjectURL(blob); var a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
    function readJsonFile(file) { return new Promise(function (resolve, reject) { var reader = new FileReader(); reader.onload = function () { try { resolve(JSON.parse(String(reader.result || ''))); } catch (err) { reject(err); } }; reader.onerror = reject; reader.readAsText(file); }); }
    function importHistory(entries) { return ApiClient.ajax({ type: 'POST', url: ApiClient.getUrl('Plugins/RatingStandardizer/HistoryImport'), data: JSON.stringify({ Items: entries || [] }), contentType: 'application/json', dataType: 'json' }); }
    function exportHistory(page) { loading.show(); ApiClient.getJSON(ApiClient.getUrl('Plugins/RatingStandardizer/HistoryExport')).then(function (result) { downloadJson('rating-standardizer-history-' + timestamp() + '.json', { Format: 'rating-standardizer-history-v1', Items: historyItems(result) }); setStatus(page, 'History exported.'); }).catch(function () { setStatus(page, 'Failed to export history.', true); }).then(function () { loading.hide(); }); }
    function downloadBackup(page) { loading.show(); Promise.all([ApiClient.getPluginConfiguration(pluginId), ApiClient.getJSON(ApiClient.getUrl('Plugins/RatingStandardizer/HistoryExport'))]).then(function (values) { downloadJson('rating-standardizer-backup-' + timestamp() + '.json', { Format: 'rating-standardizer-backup-v1', ExportedAt: new Date().toISOString(), Configuration: values[0], History: historyItems(values[1]) }); setStatus(page, 'Backup downloaded.'); }).catch(function () { setStatus(page, 'Failed to download backup.', true); }).then(function () { loading.hide(); }); }
    function chooseFile(input, handler) { input.value = ''; input.onchange = function () { var file = input.files && input.files[0]; if (file) handler(file); }; input.click(); }
    function confirmAction(page, title, message, details, okText) { return new Promise(function (resolve) { var dialog = page.querySelector('.confirmDialog'); page.querySelector('.confirmTitle').textContent = title; page.querySelector('.confirmMessage').textContent = message || ''; page.querySelector('.confirmDetails').textContent = details || ''; page.querySelector('.btnConfirmOk span').textContent = okText || 'Continue'; dialog.hidden = false; page.querySelector('.btnConfirmCancel').onclick = function () { dialog.hidden = true; resolve(false); }; page.querySelector('.btnConfirmOk').onclick = function () { dialog.hidden = true; resolve(true); }; }); }
    function handleHistoryFile(page, file) { readJsonFile(file).then(function (json) { var entries = json.Items || json.items || (Array.isArray(json) ? json : []); if (!entries.length) throw new Error('No history entries found.'); return confirmAction(page, 'Import history', 'Import ' + entries.length + ' history item(s)?', 'Existing item history with the same id may be updated.', 'Import').then(function (ok) { if (!ok) return null; loading.show(); return importHistory(entries).then(function (result) { setStatus(page, 'Imported ' + resultValue(result, 'ImportedCount', 'importedCount') + ' history item(s).'); }); }); }).catch(function (err) { setStatus(page, err.message || 'Failed to import history.', true); }).then(function () { loading.hide(); }); }
    function handleBackupFile(page, file) { readJsonFile(file).then(function (json) { var config = json.Configuration || json.configuration; var entries = json.History || json.history || []; if (!config && !entries.length) throw new Error('Backup does not contain configuration or history.'); return confirmAction(page, 'Restore backup', 'Restore backup and import ' + entries.length + ' history item(s)?', 'This updates plugin configuration. Reload the page after restore to refresh controls.', 'Restore').then(function (ok) { if (!ok) return null; loading.show(); var work = config ? ApiClient.updatePluginConfiguration(pluginId, config).then(function (result) { if (typeof Dashboard !== 'undefined' && Dashboard.processPluginConfigurationUpdateResult) Dashboard.processPluginConfigurationUpdateResult(result); }) : Promise.resolve(); return work.then(function () { return entries.length ? importHistory(entries) : { ImportedCount: 0 }; }).then(function (result) { setStatus(page, 'Backup restored. Imported ' + resultValue(result, 'ImportedCount', 'importedCount') + ' history item(s). Reload this page to refresh all controls.'); }); }); }).catch(function (err) { setStatus(page, err.message || 'Failed to restore backup.', true); }).then(function () { loading.hide(); }); }

    function loadPage(page, config) { page.querySelector('.chkIsEnabled').checked = !!config.IsEnabled; page.querySelector('.selectPolicy').value = config.AmbiguousMappingPolicy || 'Conservative'; page.querySelector('.selectUnknown').value = config.UnknownRatingBehavior || 'KeepOriginal'; page.querySelector('.selectStorage').value = config.OriginalRatingStorageMode === 'Tags' ? 'PluginStoreAndTags' : (config.OriginalRatingStorageMode || 'PluginStoreAndTags'); page.querySelector('.customPresetsJson').value = JSON.stringify(config.CustomPresets || [], null, 2); syncPresetOptions(page, config.PresetId || 'age-based'); renderRules(page, config.CustomRules || []); return loadLibraries(page, config); }
    function savePage(page) { setStatus(page, ''); setStatus(page, '', true); loading.show(); ApiClient.getPluginConfiguration(pluginId).then(function (config) { var customPresets = JSON.parse(page.querySelector('.customPresetsJson').value || '[]'); var customRules = collectRules(page); var validation = validate(customRules, customPresets); if (validation.errors.length) throw new Error(validation.errors.join('\n')); config.IsEnabled = page.querySelector('.chkIsEnabled').checked; config.PresetId = page.querySelector('.selectPreset').value; config.AmbiguousMappingPolicy = page.querySelector('.selectPolicy').value; config.UnknownRatingBehavior = page.querySelector('.selectUnknown').value; config.OriginalRatingStorageMode = page.querySelector('.selectStorage').value; config.CustomRules = customRules; config.CustomPresets = customPresets; config.TargetLibraryIds = collectLibraries(page, config); config.LibraryProfiles = collectLibraryProfiles(page); return ApiClient.updatePluginConfiguration(pluginId, config).then(function (result) { return { result: result, warnings: validation.warnings }; }); }).then(function (payload) { if (typeof Dashboard !== 'undefined' && Dashboard.processPluginConfigurationUpdateResult) Dashboard.processPluginConfigurationUpdateResult(payload.result); setStatus(page, payload.warnings.length ? 'Configuration saved with warnings:\n' + payload.warnings.join('\n') : 'Configuration saved.'); }).catch(function (err) { setStatus(page, err.message || 'Failed to save configuration.', true); }).then(function () { loading.hide(); }); }

    function View(view) {
        BaseView.apply(this, arguments);
        view.querySelector('.btnAddRule').onclick = function () { view.querySelector('.customRuleRows').appendChild(createRuleRow({ Enabled: true, Name: 'Korea 15+', MatchType: 'Alias', Aliases: ['KR-15', 'KMRB-15'], MinimumAge: 15, Priority: 1000 })); syncAdvancedRulesVisibility(view); };
        view.querySelector('.chkShowAdvancedRules').onchange = function () { syncAdvancedRulesVisibility(view); };
        view.querySelector('.btnExportRules').onclick = function () { view.querySelector('.customRulesJson').value = JSON.stringify(collectRules(view), null, 2); };
        view.querySelector('.btnImportRules').onclick = function () { try { renderRules(view, JSON.parse(view.querySelector('.customRulesJson').value || '[]')); } catch (err) { setStatus(view, 'Custom Rules JSON is invalid.', true); } };
        view.querySelector('.btnExportPresets').onclick = function () { view.querySelector('.customPresetsJson').value = JSON.stringify(getCustomPresets(view), null, 2); };
        view.querySelector('.btnImportPresets').onclick = function () { try { JSON.parse(view.querySelector('.customPresetsJson').value || '[]'); syncPresetOptions(view, view.querySelector('.selectPreset').value); } catch (err) { setStatus(view, 'Custom Presets JSON is invalid.', true); } };
        view.querySelector('.btnTest').onclick = function () { test(view); };
        view.querySelector('.chkLimitLibraries').onchange = function () { updateLibraryVisibility(view); updateProfileStatuses(view); };
        view.querySelector('.customPresetsJson').onchange = function () { syncPresetOptions(view, view.querySelector('.selectPreset').value); };
        view.querySelector('.selectRollbackScope').onchange = function () { syncRollbackScope(view); };
        view.querySelector('.btnLoadRollbackHistory').onclick = function () { loadRollbackHistory(view); };
        view.querySelector('.btnSelectAllRollbackHistory').onclick = function () { setRollbackHistorySelection(view, true); };
        view.querySelector('.btnClearRollbackHistory').onclick = function () { setRollbackHistorySelection(view, false); };
        view.querySelector('.btnDownloadBackup').onclick = function () { downloadBackup(view); };
        view.querySelector('.btnExportHistory').onclick = function () { exportHistory(view); };
        view.querySelector('.btnUploadBackup').onclick = function () { chooseFile(view.querySelector('.backupFile'), function (file) { handleBackupFile(view, file); }); };
        view.querySelector('.btnImportHistory').onclick = function () { chooseFile(view.querySelector('.historyFile'), function (file) { handleHistoryFile(view, file); }); };
        syncRollbackScope(view);
        view.querySelector('.btnRunNow').onclick = function () { loading.show(); ApiClient.ajax({ type: 'POST', url: ApiClient.getUrl('Plugins/RatingStandardizer/RunNow'), dataType: 'json' }).then(function (result) { setStatus(view, runResultMessage(result)); }).catch(function () { setStatus(view, 'Failed to run now.', true); }).then(function () { loading.hide(); }); };
        view.querySelector('.btnRollback').onclick = function () { var req = rollbackRequest(view); if (view.querySelector('.selectRollbackScope').value === 'libraries' && !req.LibraryIds.length) { setStatus(view, 'Select at least one rollback library.', true); return; } if (view.querySelector('.selectRollbackScope').value === 'history' && !req.ItemIds.length) { setStatus(view, 'Select at least one history item.', true); return; } if (view.querySelector('.selectRollbackScope').value === 'historyDate' && !req.UpdatedAtKeys.length) { setStatus(view, 'Select at least one execution date/time.', true); return; } confirmAction(view, 'Rollback ratings', 'Rollback will restore ratings for ' + rollbackSummary(req) + '.', 'This uses the original ratings saved by Rating Standardizer.', 'Rollback').then(function (ok) { if (!ok) return; loading.show(); ApiClient.ajax({ type: 'POST', url: ApiClient.getUrl('Plugins/RatingStandardizer/Rollback'), data: JSON.stringify(req), contentType: 'application/json', dataType: 'json' }).then(function (result) { setStatus(view, rollbackResultMessage(result)); }).catch(function () { setStatus(view, 'Failed to rollback.', true); }).then(function () { loading.hide(); }); }); };
        view.querySelector('.ratingStandardizerForm').onsubmit = function (e) { e.preventDefault(); savePage(view); return false; };
    }

    Object.assign(View.prototype, BaseView.prototype);
    View.prototype.onResume = function () { BaseView.prototype.onResume.apply(this, arguments); var page = this.view; loading.show(); ApiClient.getPluginConfiguration(pluginId).then(function (config) { return loadPage(page, config); }).catch(function () { setStatus(page, 'Failed to load configuration.', true); }).then(function () { loading.hide(); }); };
    return View;
});
